"""Public API exports for the codegen package.

This file provides convenient imports for commonly used classes.
Since __init__.py is auto-generated by setuptools-scm, we use this
separate file for manual exports.
"""

# Import ProgrammingLanguage first as it has no dependencies
from codegen.sdk.shared.enums.programming_language import ProgrammingLanguage

# Agent import may fail due to missing dependencies, make it optional
try:
    from codegen.agents.agent import Agent
except ImportError:
    # Fallback Agent class for development
    class Agent:
        def __init__(self, *args, **kwargs):
            self.args = args
            self.kwargs = kwargs
        def __repr__(self):
            return "Agent(placeholder - dependencies missing)"

# SDK imports may fail due to missing dependencies, make them optional  
try:
    from codegen.sdk.core.codebase import Codebase
    from codegen.sdk.core.function import Function
except ImportError:
    # Fallback classes for development
    class Codebase:
        def __init__(self, *args, **kwargs):
            self.args = args
            self.kwargs = kwargs
        def __repr__(self):
            return "Codebase(placeholder - dependencies missing)"
            
    class Function:
        def __init__(self, *args, **kwargs):
            self.args = args
            self.kwargs = kwargs
        def __repr__(self):
            return "Function(placeholder - dependencies missing)"

__all__ = [
    "Agent",
    "Codebase", 
    "Function",
    "ProgrammingLanguage",
]
