"""
Data models for the integrated agent application.
"""

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Union

from pydantic import BaseModel, Field, HttpUrl


class RequirementStatus(str, Enum):
    """Status of a requirement."""
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


class Requirement(BaseModel):
    """A requirement extracted from a document."""
    id: str = Field(..., description="Unique identifier for the requirement")
    title: str = Field(..., description="Title or short description of the requirement")
    description: str = Field(..., description="Full description of the requirement")
    source_document: str = Field(..., description="Source document name")
    section: str = Field(..., description="Section in the document")
    status: RequirementStatus = Field(default=RequirementStatus.NOT_STARTED, description="Status of the requirement")
    created_at: datetime = Field(default_factory=datetime.now, description="Creation timestamp")
    updated_at: datetime = Field(default_factory=datetime.now, description="Last update timestamp")
    assigned_pr: Optional[int] = Field(default=None, description="PR number assigned to this requirement")
    implementation_notes: Optional[str] = Field(default=None, description="Notes on implementation")


class Document(BaseModel):
    """A document containing requirements."""
    id: str = Field(..., description="Unique identifier for the document")
    name: str = Field(..., description="Name of the document")
    content: str = Field(..., description="Content of the document")
    created_at: datetime = Field(default_factory=datetime.now, description="Creation timestamp")
    updated_at: datetime = Field(default_factory=datetime.now, description="Last update timestamp")
    requirements: List[str] = Field(default_factory=list, description="List of requirement IDs extracted from this document")


class Repository(BaseModel):
    """A GitHub repository configuration."""
    id: str = Field(..., description="Unique identifier for the repository")
    name: str = Field(..., description="Name of the repository (owner/repo)")
    url: HttpUrl = Field(..., description="URL of the repository")
    webhook_id: Optional[str] = Field(default=None, description="ID of the webhook")
    webhook_url: Optional[HttpUrl] = Field(default=None, description="URL of the webhook")
    webhook_secret: Optional[str] = Field(default=None, description="Secret for the webhook")
    created_at: datetime = Field(default_factory=datetime.now, description="Creation timestamp")
    updated_at: datetime = Field(default_factory=datetime.now, description="Last update timestamp")


class PRReview(BaseModel):
    """A PR review result."""
    pr_number: int = Field(..., description="PR number")
    repository: str = Field(..., description="Repository name (owner/repo)")
    title: str = Field(..., description="PR title")
    description: str = Field(..., description="PR description")
    author: str = Field(..., description="PR author")
    created_at: datetime = Field(..., description="PR creation timestamp")
    updated_at: datetime = Field(..., description="PR update timestamp")
    status: str = Field(..., description="PR status")
    review_result: str = Field(..., description="Review result")
    review_comments: List[str] = Field(default_factory=list, description="Review comments")
    requirements_met: List[str] = Field(default_factory=list, description="Requirements met by this PR")
    requirements_not_met: List[str] = Field(default_factory=list, description="Requirements not met by this PR")


class ProjectPlan(BaseModel):
    """A project plan generated by AI."""
    id: str = Field(..., description="Unique identifier for the plan")
    title: str = Field(..., description="Title of the plan")
    description: str = Field(..., description="Description of the plan")
    repository: str = Field(..., description="Repository name (owner/repo)")
    created_at: datetime = Field(default_factory=datetime.now, description="Creation timestamp")
    updated_at: datetime = Field(default_factory=datetime.now, description="Last update timestamp")
    steps: List[Dict] = Field(default_factory=list, description="Steps in the plan")
    tree_structure: Optional[str] = Field(default=None, description="Project tree structure")


class SlackMessage(BaseModel):
    """A message sent to or received from Slack."""
    id: str = Field(..., description="Unique identifier for the message")
    channel: str = Field(..., description="Channel ID")
    text: str = Field(..., description="Message text")
    user: str = Field(..., description="User ID")
    timestamp: str = Field(..., description="Message timestamp")
    requirement_id: Optional[str] = Field(default=None, description="Related requirement ID")
    pr_number: Optional[int] = Field(default=None, description="Related PR number")